// Sık kullanılan İngilizce cümle kalıpları (lexical chunks).
// "key" her örnek cümlede birebir geçen sabit parçadır; boşluk doldurma alıştırmasında kullanılır.

export const PATTERN_CATS = [
  { id: 'self', title: 'Kendini İfade Et', emoji: '🙋', color: '#D7F75B' },
  { id: 'ask', title: 'Rica & İstek', emoji: '🙏', color: '#7CC8FF' },
  { id: 'plan', title: 'Öneri & Plan', emoji: '🗓️', color: '#FFB4D0' },
  { id: 'opinion', title: 'Görüş Bildir', emoji: '💬', color: '#8B7BFF' },
  { id: 'exp', title: 'Deneyim & Zaman', emoji: '⏳', color: '#FFD166' },
  { id: 'advice', title: 'Zorunluluk & Tavsiye', emoji: '🧭', color: '#7EE3B8' },
  { id: 'compare', title: 'Karşılaştırma & Tercih', emoji: '⚖️', color: '#FFA36C' },
  { id: 'chat', title: 'Soru & Sohbet', emoji: '❓', color: '#C9A7FF' },
  { id: 'react', title: 'Duygu & Tepki', emoji: '💥', color: '#FF6A3D' },
];

export const PATTERNS = [
  // self
  { id: 'into', cat: 'self', pattern: "I'm into + isim / V-ing", key: "I'm into", tr: '…ile ilgileniyorum / …a bayılıyorum', note: 'Hobiler ve ilgi alanları için çok doğal, gündelik bir ifade. "I like" yerine kullanınca kulağa daha akıcı gelir.', ex: [["I'm into photography.", 'Fotoğrafçılıkla ilgileniyorum.'], ["I'm into cooking these days.", 'Bu aralar yemek yapmaya bayılıyorum.'], ["I'm into jazz music.", 'Caz müziğe bayılırım.']] },
  { id: 'usedto-be', cat: 'self', pattern: "I'm used to + V-ing / isim", key: "I'm used to", tr: '…maya alışkınım', note: '"used to + V" (eskiden yapardım) ile karıştırma! Burada "to" bir edattır, ardından -ing gelir.', ex: [["I'm used to waking up early.", 'Erken kalkmaya alışkınım.'], ["I'm used to the cold weather.", 'Soğuk havaya alışkınım.'], ["I'm used to working from home.", 'Evden çalışmaya alışkınım.']] },
  { id: 'usedto', cat: 'self', pattern: 'I used to + V1', key: 'I used to', tr: 'Eskiden …rdım (artık değil)', note: 'Geçmişte düzenli olan ama artık olmayan alışkanlıklar için. Telaffuz: /ˈjuːstə/ — "yuzd tu" değil, "yusta".', ex: [['I used to play the guitar.', 'Eskiden gitar çalardım.'], ['I used to live in Ankara.', "Eskiden Ankara'da yaşardım."], ['I used to hate coffee.', 'Eskiden kahveden nefret ederdim.']] },
  { id: 'notgood', cat: 'self', pattern: "I'm (not) good at + V-ing", key: 'good at', tr: '…da iyiyim / iyi değilim', note: '"good in" değil, "good at" deriz. Ardından isim ya da -ing gelir.', ex: [["I'm not good at remembering names.", 'İsimleri hatırlamakta iyi değilim.'], ["She's good at math.", 'Matematikte iyidir.'], ["I'm good at cooking pasta.", 'Makarna yapmakta iyiyim.']] },
  { id: 'depends', cat: 'self', pattern: 'It depends on + isim', key: 'It depends on', tr: '…a bağlı', note: 'Kararsız kaldığında harika bir kaçış kalıbı. Tek başına "It depends." da kullanılır.', ex: [['It depends on the weather.', 'Havaya bağlı.'], ['It depends on the price.', 'Fiyata bağlı.'], ['It depends on my schedule.', 'Programıma bağlı.']] },

  // ask
  { id: 'couldyou', cat: 'ask', pattern: 'Could you + V1 (please)?', key: 'Could you', tr: '…abilir misiniz?', note: '"Can you"dan daha kibar. Yabancılarla ve iş ortamında güvenli seçim.', ex: [['Could you help me, please?', 'Bana yardım edebilir misiniz lütfen?'], ['Could you speak more slowly?', 'Daha yavaş konuşabilir misiniz?'], ['Could you send me the file?', 'Bana dosyayı gönderebilir misiniz?']] },
  { id: 'wouldmind', cat: 'ask', pattern: 'Would you mind + V-ing?', key: 'Would you mind', tr: '…mamın / …manızın sakıncası var mı?', note: 'Çok kibar bir rica. DİKKAT: Kabul ederken "No, not at all." (Hayır, hiç sakıncası yok) denir.', ex: [['Would you mind opening the window?', 'Pencereyi açmanızın sakıncası var mı?'], ['Would you mind waiting a minute?', 'Bir dakika beklemenizin sakıncası var mı?'], ['Would you mind closing the door?', 'Kapıyı kapatır mısınız?']] },
  { id: 'idlike', cat: 'ask', pattern: "I'd like to + V1", key: "I'd like to", tr: '…mak isterim', note: '"I want"in kibar hâli. Restoranda, otelde, telefonda en çok kullanılan kalıplardan.', ex: [["I'd like to book a table.", 'Bir masa ayırtmak istiyorum.'], ["I'd like to ask a question.", 'Bir soru sormak istiyorum.'], ["I'd like to pay by card.", 'Kartla ödemek istiyorum.']] },
  { id: 'mindif', cat: 'ask', pattern: 'Do you mind if I + V1?', key: 'Do you mind if I', tr: '…sam sakıncası var mı?', note: 'İzin isterken. Cevap "No, go ahead." (Hayır, buyrun) olursa izin verilmiştir.', ex: [['Do you mind if I sit here?', 'Buraya otursam sakıncası var mı?'], ['Do you mind if I open the window?', 'Pencereyi açsam sakıncası var mı?'], ['Do you mind if I call you later?', 'Seni sonra arasam olur mu?']] },
  { id: 'okayif', cat: 'ask', pattern: 'Is it okay if I + V1?', key: 'Is it okay if I', tr: '…sam olur mu?', note: 'Gündelik ve samimi izin isteme kalıbı.', ex: [['Is it okay if I leave early?', 'Erken çıksam olur mu?'], ['Is it okay if I use your phone?', 'Telefonunu kullansam olur mu?'], ['Is it okay if I bring a friend?', 'Bir arkadaşımı getirsem olur mu?']] },

  // plan
  { id: 'howabout', cat: 'plan', pattern: 'How about + V-ing / isim?', key: 'How about', tr: '…maya ne dersin?', note: 'Öneri yapmanın en rahat yolu. Ardından -ing veya isim gelir.', ex: [['How about going to the cinema?', 'Sinemaya gitmeye ne dersin?'], ['How about pizza tonight?', 'Bu akşam pizzaya ne dersin?'], ['How about meeting at six?', 'Altıda buluşmaya ne dersin?']] },
  { id: 'whydontwe', cat: 'plan', pattern: "Why don't we + V1?", key: "Why don't we", tr: 'Neden … yapmıyoruz? (Hadi … yapalım)', note: 'Soru gibi görünür ama aslında bir öneridir.', ex: [["Why don't we take a break?", 'Neden bir mola vermiyoruz?'], ["Why don't we order some food?", 'Neden yemek sipariş etmiyoruz?'], ["Why don't we ask the teacher?", 'Neden öğretmene sormuyoruz?']] },
  { id: 'lets', cat: 'plan', pattern: "Let's + V1", key: "Let's", tr: 'Hadi …alım', note: '"Let us"ın kısaltması. Olumsuzu: "Let\'s not…"', ex: [["Let's go for a walk.", 'Hadi yürüyüşe çıkalım.'], ["Let's start the meeting.", 'Hadi toplantıya başlayalım.'], ["Let's try again tomorrow.", 'Yarın tekrar deneyelim.']] },
  { id: 'goingto', cat: 'plan', pattern: "I'm going to + V1", key: 'going to', tr: '…acağım (planlı gelecek)', note: 'Önceden karar verilmiş planlar için. Konuşmada genelde "gonna" gibi söylenir.', ex: [["I'm going to visit my parents.", 'Ailemi ziyaret edeceğim.'], ["We're going to move next year.", 'Seneye taşınacağız.'], ["She's going to start a new job.", 'Yeni bir işe başlayacak.']] },
  { id: 'thinkingof', cat: 'plan', pattern: "I'm thinking of + V-ing", key: "I'm thinking of", tr: '…mayı düşünüyorum', note: 'Henüz kesinleşmemiş fikirler için yumuşak bir ifade.', ex: [["I'm thinking of learning Spanish.", 'İspanyolca öğrenmeyi düşünüyorum.'], ["I'm thinking of changing my job.", 'İşimi değiştirmeyi düşünüyorum.'], ["I'm thinking of buying a bike.", 'Bisiklet almayı düşünüyorum.']] },
  { id: 'lookingforward', cat: 'plan', pattern: "I'm looking forward to + V-ing", key: 'looking forward to', tr: '…u dört gözle bekliyorum', note: 'E-postaların sonunda çok kullanılır. "to"dan sonra -ing gelir: "to seeing", "to see" değil!', ex: [["I'm looking forward to seeing you.", 'Seni görmeyi dört gözle bekliyorum.'], ["I'm looking forward to the weekend.", 'Hafta sonunu iple çekiyorum.'], ["We're looking forward to working with you.", 'Sizinle çalışmayı dört gözle bekliyoruz.']] },

  // opinion
  { id: 'dontthink', cat: 'opinion', pattern: "I don't think + cümle", key: "I don't think", tr: 'Bence … değil', note: 'İngilizcede olumsuzluk "think"e yüklenir: "I think it isn\'t" yerine "I don\'t think it is" daha doğal.', ex: [["I don't think it's a good idea.", 'Bence bu iyi bir fikir değil.'], ["I don't think he's coming.", 'Onun geleceğini sanmıyorum.'], ["I don't think we have time.", 'Vaktimiz olduğunu sanmıyorum.']] },
  { id: 'opinion', cat: 'opinion', pattern: 'In my opinion, + cümle', key: 'In my opinion', tr: 'Bana göre, …', note: 'Resmî ve net bir görüş bildirme. Gündelikte "I think" daha yaygın.', ex: [['In my opinion, the film was too long.', 'Bana göre film çok uzundu.'], ['In my opinion, we should wait.', 'Bana göre beklemeliyiz.'], ['In my opinion, reading is important.', 'Bence okumak önemli.']] },
  { id: 'seemslike', cat: 'opinion', pattern: 'It seems like + cümle', key: 'It seems like', tr: 'Görünüşe göre …', note: 'Kesin olmayan izlenimler için. "It looks like" ile benzer.', ex: [["It seems like it's going to rain.", 'Yağmur yağacak gibi görünüyor.'], ['It seems like you are tired.', 'Yorgun görünüyorsun.'], ['It seems like a nice place.', 'Güzel bir yere benziyor.']] },
  { id: 'notsure', cat: 'opinion', pattern: "I'm not sure if + cümle", key: "I'm not sure if", tr: '…ıp …madığından emin değilim', note: '"if" burada "eğer" değil, "-ıp -madığı" anlamında.', ex: [["I'm not sure if he knows.", 'Bilip bilmediğinden emin değilim.'], ["I'm not sure if it's open.", 'Açık olup olmadığından emin değilim.'], ["I'm not sure if I can come.", 'Gelip gelemeyeceğimden emin değilim.']] },
  { id: 'thingis', cat: 'opinion', pattern: 'The thing is, + cümle', key: 'The thing is', tr: 'Mesele şu ki, …', note: 'Asıl sorunu ya da mazereti nazikçe açıklamak için.', ex: [["The thing is, I don't have much time.", 'Mesele şu ki pek vaktim yok.'], ['The thing is, it costs too much.', 'Mesele şu ki çok pahalı.'], ['The thing is, I already promised her.', 'Mesele şu ki ona zaten söz verdim.']] },

  // exp
  { id: 'haveyouever', cat: 'exp', pattern: 'Have you ever + V3?', key: 'Have you ever', tr: 'Hiç …dın mı?', note: 'Hayat deneyimleri için Present Perfect. Zaman belirtilmez.', ex: [['Have you ever been to London?', "Hiç Londra'ya gittin mi?"], ['Have you ever tried sushi?', 'Hiç suşi denedin mi?'], ['Have you ever seen a ghost?', 'Hiç hayalet gördün mü?']] },
  { id: 'ivebeen', cat: 'exp', pattern: "I've been + V-ing + for/since", key: "I've been", tr: '…dır …yorum', note: 'Geçmişte başlayıp hâlâ süren eylemler. Süre için "for", başlangıç noktası için "since".', ex: [["I've been learning English for two years.", 'İki yıldır İngilizce öğreniyorum.'], ["I've been waiting since nine.", 'Dokuzdan beri bekliyorum.'], ["I've been working here for a month.", 'Bir aydır burada çalışıyorum.']] },
  { id: 'beensince', cat: 'exp', pattern: "It's been + süre + since + geçmiş", key: "It's been", tr: '…dan beri … oldu', note: 'Özlem ve uzun zaman vurgusu için.', ex: [["It's been ages since I saw you.", 'Seni görmeyeli asırlar oldu.'], ["It's been a year since we met.", 'Tanışalı bir yıl oldu.'], ["It's been a long day.", 'Uzun bir gün oldu.']] },
  { id: 'ittakes', cat: 'exp', pattern: 'It takes + süre + to + V1', key: 'It takes', tr: '…mak … sürer', note: 'Süre sormak için: "How long does it take to…?"', ex: [['It takes an hour to get there.', 'Oraya gitmek bir saat sürer.'], ['It takes time to learn a language.', 'Bir dil öğrenmek zaman alır.'], ['It takes ten minutes to cook.', 'Pişirmek on dakika sürer.']] },
  { id: 'bythetime', cat: 'exp', pattern: 'By the time + cümle, …', key: 'By the time', tr: '…dığında (çoktan) …', note: 'Bir olay gerçekleştiğinde diğerinin çoktan olduğunu anlatır.', ex: [['By the time I arrived, the film had started.', 'Vardığımda film çoktan başlamıştı.'], ['By the time you wake up, I will be gone.', 'Sen uyandığında ben gitmiş olacağım.'], ['By the time we got there, the shop was closed.', 'Oraya vardığımızda dükkân kapanmıştı.']] },

  // advice
  { id: 'should', cat: 'advice', pattern: 'You should + V1', key: 'You should', tr: '…malısın (tavsiye)', note: 'Yumuşak tavsiye. Olumsuzu: "You shouldn\'t…"', ex: [['You should see a doctor.', 'Bir doktora görünmelisin.'], ['You should try this cake.', 'Bu keki denemelisin.'], ['You should get some rest.', 'Biraz dinlenmelisin.']] },
  { id: 'hadbetter', cat: 'advice', pattern: "You'd better + V1", key: "'d better", tr: '…san iyi olur (yoksa…)', note: '"should"dan daha güçlü; ima edilen bir uyarı var. "had better"ın kısaltması.', ex: [["You'd better hurry.", 'Acele etsen iyi olur.'], ["You'd better take an umbrella.", 'Şemsiye alsan iyi olur.'], ["We'd better leave now.", 'Şimdi çıksak iyi olur.']] },
  { id: 'haveto', cat: 'advice', pattern: 'I have to + V1', key: 'have to', tr: '…mak zorundayım', note: 'Dış kaynaklı zorunluluk (kural, iş). Telaffuz: /ˈhæftə/ — "hafta" gibi.', ex: [['I have to work tomorrow.', 'Yarın çalışmak zorundayım.'], ['You have to wear a helmet.', 'Kask takmak zorundasın.'], ['We have to finish this today.', 'Bunu bugün bitirmek zorundayız.']] },
  { id: 'donthaveto', cat: 'advice', pattern: "You don't have to + V1", key: "don't have to", tr: '…mak zorunda değilsin', note: 'DİKKAT: "mustn\'t" (yasak) ile aynı değil! Burada seçim sende.', ex: [["You don't have to come.", 'Gelmek zorunda değilsin.'], ["You don't have to pay.", 'Ödemek zorunda değilsin.'], ["We don't have to decide now.", 'Şimdi karar vermek zorunda değiliz.']] },
  { id: 'ifiwereyou', cat: 'advice', pattern: "If I were you, I'd + V1", key: 'If I were you', tr: 'Senin yerinde olsam …rdım', note: 'Tavsiye vermenin kibar yolu. "I was" değil "I were" (2. tip koşul).', ex: [["If I were you, I'd call her.", 'Senin yerinde olsam onu arardım.'], ["If I were you, I'd take the job.", 'Senin yerinde olsam işi kabul ederdim.'], ["If I were you, I wouldn't worry.", 'Senin yerinde olsam endişelenmezdim.']] },

  // compare
  { id: 'idrather', cat: 'compare', pattern: "I'd rather + V1 (than + V1)", key: "I'd rather", tr: '…mayı tercih ederim', note: 'Ardından "to" gelmez: "I\'d rather stay", "I\'d rather to stay" değil.', ex: [["I'd rather stay at home.", 'Evde kalmayı tercih ederim.'], ["I'd rather walk than take the bus.", 'Otobüse binmektense yürümeyi tercih ederim.'], ["I'd rather not talk about it.", 'Bu konuda konuşmamayı tercih ederim.']] },
  { id: 'themore', cat: 'compare', pattern: 'The more …, the more/-er …', key: 'The more', tr: 'Ne kadar çok …, o kadar …', note: 'İki şeyin birlikte arttığını anlatır. Motivasyon cümlesi olarak harika!', ex: [['The more you practice, the better you get.', 'Ne kadar çok pratik yaparsan o kadar iyi olursun.'], ['The more I read, the more I learn.', 'Ne kadar çok okursam o kadar çok öğrenirim.'], ['The more you sleep, the better you feel.', 'Ne kadar çok uyursan kendini o kadar iyi hissedersin.']] },
  { id: 'notas', cat: 'compare', pattern: 'It\'s not as + sıfat + as …', key: 'not as', tr: '… kadar … değil', note: 'Kibarca "daha az" demenin yolu.', ex: [["It's not as hard as it looks.", 'Göründüğü kadar zor değil.'], ["This phone is not as expensive as that one.", 'Bu telefon öteki kadar pahalı değil.'], ["He's not as tall as his brother.", 'Kardeşi kadar uzun değil.']] },
  { id: 'prefer', cat: 'compare', pattern: 'I prefer X to Y', key: 'prefer', tr: "X'i Y'ye tercih ederim", note: '"than" değil "to" kullanılır: "I prefer tea to coffee."', ex: [['I prefer tea to coffee.', 'Çayı kahveye tercih ederim.'], ['I prefer walking to running.', 'Yürümeyi koşmaya tercih ederim.'], ['Do you prefer the city or the countryside?', 'Şehri mi tercih edersin, kırsalı mı?']] },

  // chat
  { id: 'whatmean', cat: 'chat', pattern: 'What do you mean (by …)?', key: 'What do you mean', tr: '(…) ne demek istiyorsun?', note: 'Anlamadığında konuşmayı akışta tutar. Hayat kurtarır!', ex: [['What do you mean by that?', 'Bununla ne demek istiyorsun?'], ['What do you mean, it\'s closed?', 'Nasıl yani, kapalı mı?'], ['Sorry, what do you mean?', 'Pardon, ne demek istiyorsun?']] },
  { id: 'howlong', cat: 'chat', pattern: 'How long does it take to + V1?', key: 'How long does it take', tr: '…mak ne kadar sürer?', note: '"It takes…" kalıbının soru hâli.', ex: [['How long does it take to get to the airport?', 'Havalimanına gitmek ne kadar sürer?'], ['How long does it take to learn English?', 'İngilizce öğrenmek ne kadar sürer?'], ['How long does it take to cook rice?', 'Pilav pişirmek ne kadar sürer?']] },
  { id: 'whatslike', cat: 'chat', pattern: "What's … like?", key: 'like?', tr: '… nasıl bir şey / nasıl biri?', note: 'Buradaki "like" sevmek değil, "gibi" anlamında. Kişi, yer, hava durumu sormak için.', ex: [["What's the weather like?", 'Hava nasıl?'], ["What's your new boss like?", 'Yeni patronun nasıl biri?'], ["What's London like?", 'Londra nasıl bir yer?']] },
  { id: 'happentoknow', cat: 'chat', pattern: 'Do you happen to know + soru?', key: 'Do you happen to know', tr: 'Acaba … biliyor musunuz?', note: 'Yabancılara kibarca bilgi sorma. Ardından düz cümle sırası gelir: "where the station is".', ex: [['Do you happen to know where the station is?', 'Acaba istasyonun nerede olduğunu biliyor musunuz?'], ['Do you happen to know his number?', 'Acaba numarasını biliyor musun?'], ['Do you happen to know what time it is?', 'Acaba saatin kaç olduğunu biliyor musunuz?']] },
  { id: 'howcome', cat: 'chat', pattern: 'How come + düz cümle?', key: 'How come', tr: 'Nasıl oluyor da …?', note: '"Why"ın gündelik hâli; ama cümle sırası DEĞİŞMEZ: "How come you are late?"', ex: [['How come you are so happy?', 'Nasıl oluyor da bu kadar mutlusun?'], ["How come you didn't call me?", 'Nasıl oldu da beni aramadın?'], ['How come it is so cheap?', 'Nasıl bu kadar ucuz?']] },

  // react
  { id: 'cantwait', cat: 'react', pattern: "I can't wait to + V1", key: "I can't wait to", tr: '…mak için sabırsızlanıyorum', note: 'Heyecanı ifade etmenin en enerjik yolu.', ex: [["I can't wait to see you!", 'Seni görmek için sabırsızlanıyorum!'], ["I can't wait to start my holiday.", 'Tatilime başlamak için sabırsızlanıyorum.'], ["I can't wait to try it.", 'Denemek için sabırsızlanıyorum.']] },
  { id: 'sorrytohear', cat: 'react', pattern: "I'm sorry to hear (that) …", key: 'sorry to hear', tr: '…a üzüldüm', note: 'Kötü bir haber aldığında empati göstermek için. Kısa hâli: "Sorry to hear that."', ex: [["I'm sorry to hear that.", 'Buna üzüldüm.'], ["I'm sorry to hear you're sick.", 'Hasta olduğuna üzüldüm.'], ["We're sorry to hear about your loss.", 'Kaybınız için çok üzgünüz.']] },
  { id: 'feellike', cat: 'react', pattern: 'I feel like + V-ing', key: 'feel like', tr: 'Canım …mak istiyor', note: 'İstek ve ruh hâlini anlatır. "I feel like pizza" = Canım pizza çekti.', ex: [['I feel like going out tonight.', 'Bu akşam canım dışarı çıkmak istiyor.'], ["I don't feel like cooking.", 'Canım yemek yapmak istemiyor.'], ['I feel like a cup of tea.', 'Canım bir fincan çay çekti.']] },
  { id: 'nowonder', cat: 'react', pattern: 'No wonder + cümle', key: 'No wonder', tr: 'Hiç şaşırmadım / Belli ki …', note: 'Bir şeyin sebebini anladığında kullanılır.', ex: [["No wonder you're tired.", 'Yorgun olmana şaşmamalı.'], ['No wonder it was so cheap.', 'Belli ki o yüzden bu kadar ucuzmuş.'], ["No wonder she's happy.", 'Mutlu olmasına şaşmamalı.']] },
  { id: 'nouse', cat: 'react', pattern: "It's no use + V-ing", key: 'no use', tr: '…manın faydası yok', note: 'Çaresizlik ya da kabullenme ifadesi.', ex: [["It's no use crying about it.", 'Buna ağlamanın faydası yok.'], ["It's no use calling him now.", 'Onu şimdi aramanın faydası yok.'], ["It's no use worrying.", 'Endişelenmenin faydası yok.']] },
];

export const getPattern = id => PATTERNS.find(p => p.id === id);
